---
- block:
  - name: install git
    yum:
      name: git
  become: true
  become_user: root

- block:
    - name: git checkout
      vars:
        dest_prefix: "{{ user.home+'/' if not download.dest.path.startswith('/') }}"
      git:
        dest: "{{ dest_prefix }}{{ download.dest.path }}"
        repo: "{{ download.src.repo.path }}"
        version: "{{ download.src.repo.version|default('HEAD') }}"
      notify: "{{ notifiers|default([]) }}"
  become: true
  become_user: "{{ user.user }}"
