- block:
  - name: install unzip
    yum:
      name:
        - unzip
      state: installed

  - name: create dest dir
    file:
      path: "{{download.dest.path}}"
      state: directory
      owner: "{{download.user.user|default(omit)}}"

  - name: download package
    unarchive:
      src: "{{download.src.url.path}}"
      dest: "{{download.dest.path}}"
      remote_src: True
      owner: "{{download.user.user|default(omit)}}"
    when: download.src.unpack|default(False)
    notify: "{{notifiers|default([])}}"
  become: True
