- block:
  - name: install unzip
    yum:
      name:
        - unzip
      state: installed

  - name: create dest dir
    vars:
      dest_prefix: "{{ user.home+'/' if not download.dest.path.startswith('/') }}"
    file:
      path: "{{ dest_prefix }}{{ download.dest.path }}"
      state: directory
      owner: "{{ download.user.user|default(omit) }}"
      mode: 0755

  - name: download package and unpack
    vars:
      dest_prefix: "{{ user.home+'/' if not download.dest.path.startswith('/') }}"
    unarchive:
      src: "{{ download.src.url.path }}"
      dest: "{{ dest_prefix }}{{ download.dest.path }}"
      remote_src: True
      owner: "{{ download.user.user|default(omit) }}"
    when: download.src.unpack|default(False)
    notify: "{{ notifiers|default([]) }}"
  become: True
